language: php
php:
 - '5.4'
 - '5.5'
 - '5.6'
 - '7.0'
 - '7.1'
before_script:
 - git config --global user.email "you@example.com"
 - git config --global user.name "Your Name"
# - git checkout -b master
 - phpenv config-add travis.php.ini
script:
 - phpunit phpcf-src/test/PhpCfTest.php
# - phpunit phpcf-src/test/PhpCfFunctional.php --debug
